apiVersion: sagemaker.aws.amazon.com/v1
kind: HostingAutoscalingPolicy
metadata:
  name: ep-autoscaling-custom
spec:
    resourceId:
      - endpointName: xgboost-2020-06-01-20-39-37-305
        variantName: AllTraffic
    region: us-east-2
    policyName: SageMakerEndpointInvocationScalingPolicy
    policyType: TargetTrackingScaling
    minCapacity: 1
    maxCapacity: 1
    targetTrackingScalingPolicyConfiguration:
        targetValue: 60.0 
        scaleInCooldown: 700 
        scaleOutCooldown: 300
        customizedMetricSpecification: 
          metricName: CPUUtilization 
          namespace: /aws/sagemaker/Endpoints 
          dimensions:  
             - name: EndpointName
               value: xgboost-2020-06-01-20-39-37-305
             - name: VariantName
               value: AllTraffic
          statistic: Average 
          unit: Percent
